### ISSUE TITLE
Add Direct ZMQ Connection Support

### ISSUE THREAD

**Issue by lukeswitz** [Root-Down-Digital/DragonSync-iOS#4]
### Publisher Updates:
Bind zmq.PUB sockets to ports 4224 (Remote ID) provided by DroneID’s ZMQ decoder.

### App Changes:
- Add a UI option to select between multicast or direct ZMQ connection.
- Use a ZMQ in Apple Network library to implement direct TCP connections (tcp://server-ip:4224 and tcp://server-ip:4225).

### Testing:
- Validate multicast and direct connectivity independently and simultaneously.
- Ensure proper data flow regardless of selected mode.

#### Documentation:
Update README with connection configuration and UI selection instructions.

**Comment by alphafox02** [comment]
Bind zmq.PUB sockets to ports 4224 (Remote ID) provided by DroneID’s ZMQ decoder. 

Might be a better description? At the point it’s coming of the ZMQ port it’s not been converted to CoT yet.

**Comment by lukeswitz** [comment]
Absolutely

**Comment by alphafox02** [comment]
Being able to select between two techniques is great. If people are not interested in TAK related stuff, they can avoid running the DragonSync repo script and connect direct to data coming off the ZMQ server that’s feeding DragonSync.
